### ISSUE TITLE
Ability to approve pull request multiple times

### ISSUE THREAD

**Issue by tristanbes** [hmarr/auto-approve-action#13]
Hello,

On a repository, we have a rule that force 2 reviewers minimum;

Would you think it'd be possible to configure this action to approve twice (or any configurable numbers) the pull request ?

Thanks;

**Comment by dannyshaw** [comment]
I gave this a go as we also require a second review but would like to waive this for certain PRs (dependabot)

It turns out even using a third party api token results in the Review Approval coming from `github-actions[bot]`. 

I really wish Github would just allow certain users to be exempt from the rules.

**Comment by ladhadeepak** [comment]
Hello @hmarr, @tristanbes, @dannyshaw,

We are facing the same situation - 2 minimum reviewers are needed per PR but want bot (or bots) to approve certain auto-promote PRs (for dependency update etc.) twice so that it can be auto-merged without external intervention.

I see that it is a 5-year-old question and hence wondering if there was any further update on it?

Thank you very much.

**Comment by hmarr** [comment]
If you're willing to use multiple bot accounts (which I think is necessary given the discussion above), you might be able to just run this action multiple times with different tokens. Have you tried that?

**Comment by hkoso-softserve** [comment]
@hmarr Bots with multiple tokens work fine, thank you

However, you should consider that you can`t be the approver of your own PRs. So approvers with tokens should always be reviewers who can approve changes.
