### ISSUE TITLE
Action "succeeds" but does not actually add a review

### ISSUE THREAD

**Issue by tjann** [hmarr/auto-approve-action#147]
<img width="663" alt="Screen Shot 2020-08-10 at 6 45 44 PM" src="https://user-images.githubusercontent.com/18621425/89847893-f64bc100-db39-11ea-965d-458d10b84c8f.png">

I added the action, then updated a PR, then saw the action run. However, while the action succeeded, no approval was added to the PR. Am I doing something wrong? I saw the "Run hmarr/auto-approve-action" is a grey circle rather than a green checkmark-- did it fail to actually run? Here is the [PR](https://github.com/datacommonsorg/data/pull/205).

**Comment by hmarr** [comment]
Thanks for reporting this. I'm not entirely sure why it was skipped in that case - I think that generally only happens when the `if` condition isn't met.

It might be helpful to [dump the context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-printing-context-information-to-the-log-file) to the logs to figure out why the actor expression isn't working.

If it turns out to be a problem with the workflow syntax suggested in the README, please report back and I'll get it fixed!

In the meantime I'll close this as I don't think it's a problem with the action itself.
