### ISSUE TITLE
Approval of a PR made by another action

### ISSUE THREAD

**Issue by freearhey** [hmarr/auto-approve-action#21]
Is it possible to run this action right after another action has created a pull request?

Neither `push` event nor `pull_request` in my case trigger this action.

At the same time, it’s also not very clear how to correctly filter PR made by an action. Should it be `if: github.actor == 'github-action'` or `if: github.actor == 'github-action[bot]'` or something else?

**Comment by hmarr** [comment]
I don't think that's possible. From https://help.github.com/en/articles/events-that-trigger-workflows#about-workflow-events:

> An action in a workflow run can't trigger a new workflow run. For example, if an action pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

I assume this is to prevent infinite chains of actions being triggered.

**Comment by freearhey** [comment]
Thanks for the answer!

**Comment by roryabraham** [comment]
Now that Github Actions has the [workflow_dispatch event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch), I think it _is_ possible to trigger one workflow from another. So I would love it if this action took an optional input for the pull request number, because then it can be used from a workflow that executes on the `workflow_dispatch` event.

**Comment by roryabraham** [comment]
I know I can't reopen this issue, but I did create a pull request to implement the functionality I want here, if you're interested.
