### ISSUE TITLE
Github actions rate limit

### ISSUE THREAD

**Issue by tristanbes** [hmarr/auto-approve-action#6]
Hello again,

When working with large repositories number (we currently have 300+) on which 50+% of them have dependabot.

When we manage to deploy the `auto-approve-action` to all of those repositories, i'm afraid, we're going to hit the limit since dependabot is set to open pull requests on daily or weekly basis on those repositories. 

Do you have any hints on this subject ?

**Comment by hmarr** [comment]
Are you referring to [this rate limit](https://developer.github.com/actions/changes/2019-06-04-actions-rate-limiting/). I wasn't aware of that previously.

I'm not sure what happens when you breach the rate limit - if the Actions are just queued up then you should be fine. If they get cancelled, then one options would be to spread out the timings for dependabot update runs, as the rate limit is applied per minute. I know that's not a particularly satisfying answer. Another option would be to effectively do what this action does yourself in CI.

**Comment by tristanbes** [comment]
Can you check internally withing Github what happens if rate limit is reached please ? 

The ideal would be to be queued, otherwise, the CI solution is far from ideal because it means Github actions has no/little value for high repositories organisations with dependabot :(

**Comment by tristanbes** [comment]
I've also raised this issue via Github Support.

**Comment by hmarr** [comment]
Great, thanks - that's probably the quickest route. If you don't hear anything back next week, let me know and I'll try to nudge it along (I'm away next week but will be checking emails).

**Comment by tristanbes** [comment]
Follow up on the subject, here's the Github support reply:

> Assuming these are rate limits for workflow executions, yes. Our current rate limit rule is 20 workflow executions per minute. In the event that you need to execute larger builds, we have included a burst of 15 additional executions available to you in the same minute window. Our team wrote a blog post about this here:

> https://developer.github.com/actions/changes/2019-06-04-actions-rate-limiting/

I don't know if we should be worried 🤷‍♂️

**Comment by hmarr** [comment]
Closing this for now as it's not an issue with action specifically.
